<script setup lang="ts">
import { ref } from 'vue'
import { api } from '../../services/api'
const props = defineProps<{ admissionId: number; patientName: string }>()
const emit = defineEmits<{ saved: [] ; close: [] }>()
const types = ['Medical Certificate','Laboratory Result','Imaging Result','Discharge Summary','Clinical Notes','Prescription','Other']
const documentType = ref<string>(types[0] ?? 'Other'); const documentDate = ref(new Date().toISOString().slice(0,10)); const file = ref<File>(); const saving = ref(false); const submitted = ref(false); const error = ref('')
function pick(event: Event) { file.value = (event.target as HTMLInputElement).files?.[0] }
async function toBase64(input: File): Promise<string> { const bytes = new Uint8Array(await input.arrayBuffer()); const chunkSize = 0x8000; let binary = ''; for (let offset = 0; offset < bytes.length; offset += chunkSize) binary += String.fromCharCode(...bytes.subarray(offset, offset + chunkSize)); return btoa(binary) }
async function save() { if (saving.value || submitted.value) return; if (!file.value) { error.value = 'Choose a demo file first.'; return }; saving.value = true; error.value = ''; try { const base64 = await toBase64(file.value); await api.createDocument({ admissionId: props.admissionId, documentType: documentType.value, documentDate: documentDate.value, fileName: file.value.name, uploadedBy: 'Demo Records Staff', contentBase64: base64 }); submitted.value = true; emit('saved') } catch (e) { error.value = e instanceof Error ? e.message : 'Could not save document' } finally { saving.value = false } }
</script>
<template>
  <div class="fixed inset-0 z-50 grid place-items-center bg-[#0b1425]/60 p-4 backdrop-blur-sm" @click.self="emit('close')"><div class="w-full max-w-[540px] rounded-3xl bg-white p-7 shadow-2xl"><div class="mb-6 flex items-start justify-between"><div><div class="mb-2 text-xs font-bold uppercase tracking-[.15em] text-[#1b9e8c]">Demo document intake</div><h2 class="display text-2xl font-bold">Add document</h2><p class="mt-1 text-sm text-[#7b8799]">For {{ patientName }} · synthetic record workflow</p></div><button class="grid h-9 w-9 place-items-center rounded-full bg-[#f2f5f8] text-[#718096]" @click="emit('close')"><span class="material-symbols-rounded">close</span></button></div><div class="space-y-5"><label class="block"><span class="mb-2 block text-xs font-bold uppercase tracking-wider text-[#69778d]">Document type</span><select v-model="documentType" class="w-full rounded-xl border border-[#dde5ee] bg-white px-4 py-3 text-sm outline-none focus:border-[#39b9a6]"><option v-for="type in types" :key="type">{{ type }}</option></select></label><label class="block"><span class="mb-2 block text-xs font-bold uppercase tracking-wider text-[#69778d]">Document date</span><input v-model="documentDate" type="date" class="w-full rounded-xl border border-[#dde5ee] px-4 py-3 text-sm outline-none focus:border-[#39b9a6]" /></label><label class="flex cursor-pointer flex-col items-center rounded-2xl border-2 border-dashed border-[#c9d9e5] bg-[#f8fbfc] px-6 py-8 text-center hover:border-[#48bbaa]"><span class="material-symbols-rounded mb-2 text-3xl text-[#27aa97]">upload_file</span><span class="text-sm font-bold text-[#34445b]">{{ file?.name ?? 'Choose a demo file' }}</span><span class="mt-1 text-xs text-[#8a98aa]">Files are stored locally under backend/uploads/demo</span><input type="file" class="hidden" accept=".pdf,.png,.jpg,.jpeg,.txt" @change="pick" /></label><p v-if="error" class="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{{ error }}</p></div><div class="mt-7 flex justify-end gap-3"><button class="rounded-xl px-4 py-3 text-sm font-bold text-[#69778d] hover:bg-[#f1f5f8]" @click="emit('close')">Cancel</button><button class="flex items-center gap-2 rounded-xl bg-[#1c9f8d] px-5 py-3 text-sm font-bold text-white shadow-lg shadow-[#1c9f8d]/20 disabled:opacity-50" :disabled="saving" @click="save"><span class="material-symbols-rounded text-base">save</span>{{ saving ? 'Saving…' : 'Save document' }}</button></div></div></div>
</template>
